### ISSUE TITLE
Pandas/Numpy error after pressing the "Change Chart" button

### ISSUE THREAD

**Issue by gdtraveller** [alex314159/wxmatplotlibexamples#1]
HI,
The following traceback occurs after pressing the "Change Chart" button.

Traceback (most recent call last):
  File "wxcharts.py", line 281, in on_change_chart
    BaseChart('Line chart', 'x', 'y', 8, self.bottom_panel, False).line(df)
  File "wxcharts.py", line 89, in line
    df.plot(ax=self.ax)
  File "/usr/lib/python3/dist-packages/pandas/plotting/_core.py", line 794, in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)
  File "/usr/lib/python3/dist-packages/pandas/plotting/_matplotlib/__init__.py", line 62, in plot
    plot_obj.generate()
  File "/usr/lib/python3/dist-packages/pandas/plotting/_matplotlib/core.py", line 279, in generate
    self._compute_plot_data()
  File "/usr/lib/python3/dist-packages/pandas/plotting/_matplotlib/core.py", line 403, in _compute_plot_data
    numeric_data = data.select_dtypes(
  File "/usr/lib/python3/dist-packages/pandas/core/frame.py", line 3442, in select_dtypes
    include_these = Series(not bool(include), index=self.columns)
  File "/usr/lib/python3/dist-packages/pandas/core/series.py", line 314, in __init__
    data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True)
  File "/usr/lib/python3/dist-packages/pandas/core/internals/construction.py", line 712, in sanitize_array
    subarr = construct_1d_arraylike_from_scalar(value, len(index), dtype)
  File "/usr/lib/python3/dist-packages/pandas/core/dtypes/cast.py", line 1241, in construct_1d_arraylike_from_scalar
    subarr = np.empty(length, dtype=dtype)
TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

I'm using the following software versions.
system: Linux trogon 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

python: Python 3.8.10 (default, Nov 26 2021, 20:14:08) 

numpy: In [3]: numpy.__version__                                                                                                                                                                     
Out[3]: '1.22.2'

pandas:In [5]: pandas.__version__                                                                                                                                                                    
Out[5]: '0.25.3'

matplotlib:In [7]: matplotlib.__version__                                                                                                                                                                
Out[7]: '3.1.2'

wxpython: In [9]: wx.__version__                                                                                                                                                                        
Out[9]: '4.0.7'

Any help would be appreciated.
Thanks

**Comment by alex314159** [comment]
ha, I didn't know anyone still used that! Just checked and working on windows, using numpy 1.18.5 and pandas 1.0.5. Happy to try but can you update pandas maybe? Your version seems quite old (so is mine actually!)

**Comment by gdtraveller** [comment]
Thanks for your quick reply.
The 0.25.3 version of pandas is the latest available for Ubuntu 20.
Let me try to setup a venv with the latest published version of pandas.
Thanks again for your help.


    On Wednesday, March 16, 2022, 08:09:59 a.m. EDT, alex314159 ***@***.***> wrote:  
 


ha, I didn't know anyone still used that! Just checked and working on windows, using numpy 1.18.5 and pandas 1.0.5. Happy to try but can you update pandas maybe? Your version seems quite old (so is mine actually!)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
